// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EM.Comax.ShukHerzel.Models.Models;

public partial class AllItem
{
    public long Id { get; set; }

    public long CompanyId { get; set; }

    public long BranchId { get; set; }

    public DateTime CreatedDateTime { get; set; }

    public bool IsTransferredToOper { get; set; }

    public DateTime? TransferredDateTime { get; set; }

    public bool IsBad { get; set; }

    public Guid OperationGuid { get; set; }

    public string Name { get; set; }

    public string Size { get; set; }

    public string XmlId { get; set; }

    public string OldId { get; set; }

    public string AnotherBarkods { get; set; }

    public string WebShortName { get; set; }

    public string WebDesc { get; set; }

    public string WebDesc2 { get; set; }

    public string WebDelvDesc { get; set; }

    public string WebInstruction { get; set; }

    public string Barcode { get; set; }

    public string PurchasingAccountId { get; set; }

    public string SalesAccountId { get; set; }

    public string AlternateId { get; set; }

    public string WorkByAlternateId { get; set; }

    public string SerialNo { get; set; }

    public string Price { get; set; }

    public string Quantity { get; set; }

    public string DiscountPercent { get; set; }

    public string DiscountTotal { get; set; }

    public string TotalSum { get; set; }

    public string MaxQuantityInOrder { get; set; }

    public string CorrectionPrice { get; set; }

    public string CorrectionDiscountPercent { get; set; }

    public string CorrectionQuantity { get; set; }

    public string ConversionQuantity { get; set; }

    public string SuperDepartment { get; set; }

    public string SuperDepartmentCode { get; set; }

    public string Department { get; set; }

    public string DepartmentCode { get; set; }

    public string DepartmentEnglishName { get; set; }

    public string GroupName { get; set; }

    public string GroupCode { get; set; }

    public string GroupEnglishName { get; set; }

    public string SubGroup { get; set; }

    public string SubGroupCode { get; set; }

    public string SubGroupEnglishName { get; set; }

    public string Manufacturer { get; set; }

    public string ManufacturerCode { get; set; }

    public string ItemModelName { get; set; }

    public string ItemModelId { get; set; }

    public string ItemColorName { get; set; }

    public string ItemColorId { get; set; }

    public string ItemSizeName { get; set; }

    public string ItemSizeId { get; set; }

    public string ItemsTree { get; set; }

    public string Attribute1 { get; set; }

    public string Attribute1Code { get; set; }

    public string Attribute2 { get; set; }

    public string Attribute2Code { get; set; }

    public string Attribute3 { get; set; }

    public string Attribute3Code { get; set; }

    public string Attribute4 { get; set; }

    public string Attribute4Code { get; set; }

    public string Attribute5 { get; set; }

    public string Attribute5Code { get; set; }

    public string SupplierId { get; set; }

    public string SupplierName { get; set; }

    public string SupplierCatalogNumber { get; set; }

    public string SupplierPrice { get; set; }

    public string SupplierCurrency { get; set; }

    public string SupplierShekelPrice { get; set; }

    public string SupplierPriceNet { get; set; }

    public string SupplierShekelPriceNet { get; set; }

    public string ArchiveDate { get; set; }

    public string BlockPurchaseDate { get; set; }

    public string BlockSalesDate { get; set; }

    public string EnglishName { get; set; }

    public string PromoId { get; set; }

    public string PromoRank { get; set; }

    public string MatchingItemId { get; set; }

    public string MatchingItemQuantity { get; set; }

    public string UnitsQuantity { get; set; }

    public string Length { get; set; }

    public string LengthSize { get; set; }

    public string Width { get; set; }

    public string WidthSize { get; set; }

    public string Height { get; set; }

    public string HeightSize { get; set; }

    public string Weight { get; set; }

    public string WeightSize { get; set; }

    public string CurrentStoreId { get; set; }

    public string BaseLine { get; set; }

    public string BaseDocNumber { get; set; }

    public string BaseReference { get; set; }

    public string BaseYear { get; set; }

    public string Conversion { get; set; }

    public string AdditionalConversion { get; set; }

    public string NotShowInWeb { get; set; }

    public string LinkWebSite { get; set; }

    public string SetModelProperties { get; set; }

    public string HierarchyUpdate { get; set; }

    public string DownloadPriceTransparencyAfter48Hours { get; set; }

    public string ItemData { get; set; }

    public string RejectTypeId { get; set; }

    public string OpenDate { get; set; }

    public string WarrantyMonths { get; set; }

    public string Ingredients { get; set; }

    public string FullIngredientsReplace { get; set; }

    public string CmtAmara { get; set; }

    public string AmaraBy { get; set; }

    public string CmtAmara2 { get; set; }

    public string InternalAmara { get; set; }

    public string Line { get; set; }

    public string LengthOptic { get; set; }

    public string DiagonalOptic { get; set; }

    public string HeightOptic { get; set; }

    public string NameInWeb { get; set; }

    public string NosafKod2 { get; set; }

    public string NosafNm2 { get; set; }

    public string NosafKod3 { get; set; }

    public string NosafNm3 { get; set; }

    public string AtarDescription { get; set; }

    public string Energia { get; set; }

    public string Pahmemot { get; set; }

    public string Helbonim { get; set; }

    public string Shumanim { get; set; }

    public string Colestrol { get; set; }

    public string MhrMivza { get; set; }

    public string SwBonos { get; set; }

    public string BonosFline { get; set; }

    public string BonosTline { get; set; }

    public string MirshamPhrmaSoft { get; set; }

    public string CustomerMakat { get; set; }

    public string QtyType { get; set; }

    public string NoDiscount { get; set; }

    public string PriceUsd { get; set; }

    public string PriceNis { get; set; }

    public string WarrantySupplier { get; set; }

    public string WarrantyRemark { get; set; }

    public string Content { get; set; }

    public string ContentUnit { get; set; }

    public string ContentMeasure { get; set; }

    public string Volume { get; set; }

    public string VolumeSize { get; set; }

    public string SwWeighable { get; set; }

    public string Radius { get; set; }

    public string Nava { get; set; }

    public string Thickness { get; set; }

    public string MinStock { get; set; }

    public string MaxStock { get; set; }

    public string SuppliersOrders { get; set; }

    public string CustomersOrders { get; set; }

    public string SwSerialy { get; set; }

    public string StoreId { get; set; }

    public string NetPrice { get; set; }

    public string CmtAmr3 { get; set; }

    public string MidaAmr3 { get; set; }

    public string NmMashlim { get; set; }

    public string WebManufacturer { get; set; }

    public string WebManufacturerCode { get; set; }

    public string WebCategory { get; set; }

    public string WebSubGroup { get; set; }

    public string WebColor { get; set; }

    public string WebDep { get; set; }

    public string WebGrp { get; set; }

    public string WebNosafKod2 { get; set; }

    public string WebNosafNm2 { get; set; }

    public string IsGiftCardPurchase { get; set; }

    public string WebColorNm { get; set; }

    public string WebDepNm { get; set; }

    public string WebGrpNm { get; set; }

    public string WebSubGroupNm { get; set; }

    public string WebCategoryNm { get; set; }

    public string WebRating { get; set; }

    public string LimitAge { get; set; }

    public string SwPikadon { get; set; }

    public string TrailingItem { get; set; }

    public string KodSet { get; set; }

    public string SetId { get; set; }

    public string MinimumStock { get; set; }

    public string MaximumStock { get; set; }

    public string StiaAm { get; set; }

    public string NosafKod4 { get; set; }

    public string NosafNm4 { get; set; }

    public string NosafKod5 { get; set; }

    public string NosafNm5 { get; set; }

    public string NosafKod6 { get; set; }

    public string NosafNm6 { get; set; }

    public string NosafKod7 { get; set; }

    public string NosafNm7 { get; set; }

    public string NosafKod8 { get; set; }

    public string NosafNm8 { get; set; }

    public string NosafKod9 { get; set; }

    public string NosafNm9 { get; set; }

    public string NosafKod10 { get; set; }

    public string NosafNm10 { get; set; }

    public string SwAlcohol { get; set; }

    public string SwMustCmtInKupa { get; set; }

    public string ManufacturingCountry { get; set; }

    public string PikadonCmt { get; set; }

    public string IsControlledItem { get; set; }

    public string MinQtyForSale { get; set; }

    public string MaxQtyForSale { get; set; }

    public string PrtC { get; set; }

    public string ColorGrp { get; set; }

    public string RefLine { get; set; }
}