// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EM.Comax.ShukHerzel.Models.Models;

public partial class BadItemLog
{
    public long Id { get; set; }

    public string Barcode { get; set; }

    public string Message { get; set; }

    public string Guid { get; set; }

    public DateTime? TimeStamp { get; set; }
}