// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EM.Comax.ShukHerzel.Models.Models;

public partial class Company
{
    public long Id { get; set; }

    public string Description { get; set; }

    public DateTime? CreateDate { get; set; }
}