// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EM.Comax.ShukHerzel.Models.Models;

public partial class Configuration
{
    public long Id { get; set; }

    public long CompanyId { get; set; }

    public string EslUrl { get; set; }

    public string EslApiKey { get; set; }

    public long? ItemId { get; set; }

    public long? DepartmentId { get; set; }

    public long? GroupId { get; set; }

    public long? SubGroupId { get; set; }

    public long? ItemModelId { get; set; }

    public long? ItemColorId { get; set; }

    public long? ItemSizeId { get; set; }

    public string ExtraCatalogParamsJson { get; set; }

    public long? StoreIdforOpenOrdersOffset { get; set; }

    public long? SupplierId { get; set; }

    public long? CustomerId { get; set; }

    public string LoginId { get; set; }

    public string LoginPassword { get; set; }

    public string ComaxApiUrl { get; set; }

    public bool? ShowInWeb { get; set; }

    public bool? WithOutArchive { get; set; }

    public bool? SelByPriceList { get; set; }

    public DateTime? PromotionLastUpdatedDate { get; set; }

    public bool? PromotionJustActive { get; set; }

    public string PromotionStoreList { get; set; }

    public string PromotionParamsJson { get; set; }

    public DateTime CreatedDateTime { get; set; }

    public DateTime? ModifiedDateTime { get; set; }
}