// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EM.Comax.ShukHerzel.Models.Models;

public partial class ErrorLog
{
    public long LogId { get; set; }

    public string SourceName { get; set; }

    public string Request { get; set; }

    public string ExceptionMessage { get; set; }

    public string InnerException { get; set; }

    public DateTime? CreateDate { get; set; }
}