// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EM.Comax.ShukHerzel.Models.Models;

public partial class GuidToFlow
{
    public int Id { get; set; }

    public int? BranchId { get; set; }

    public string Guid { get; set; }

    public DateTime? CreateDate { get; set; }
}