// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EM.Comax.ShukHerzel.Models.Models;

public partial class Item
{
    public long Id { get; set; }

    public Guid? OperationGuid { get; set; }

    public DateTime? CreateDateTime { get; set; }

    public bool? IsSentToEsl { get; set; }

    public DateTime? SentToEslDate { get; set; }

    public long? BranchId { get; set; }

    public long? CompanyId { get; set; }

    public string Barcode { get; set; }

    public string XmlId { get; set; }

    public string Name { get; set; }

    public decimal? Price { get; set; }

    public string Size { get; set; }

    public string ManufacturingCountry { get; set; }

    public string Content { get; set; }

    public string ContentUnit { get; set; }

    public string ContentMeasure { get; set; }

    public decimal? ContentPrice { get; set; }

    public decimal? Quantity { get; set; }

    public bool? SwPikadon { get; set; }

    public string TrailingItem { get; set; }

    public bool? IsPromotion { get; set; }

    public decimal? TotalPromotionPrice { get; set; }

    public DateTime? PromotionFromDate { get; set; }

    public DateTime? PromotionToDate { get; set; }

    public string PromotionKod { get; set; }

    public string TotalForActivate { get; set; }

    public string PromotionQuantity { get; set; }

    public string GetDiscountTotal { get; set; }

    public string GetCmt { get; set; }

    public string GetDiscountPrecent { get; set; }

    public string GetTotal { get; set; }

    public string PromotionMinQty { get; set; }

    public string PromotionMaxQty { get; set; }

    public string Rating { get; set; }

    public bool? SwAllCustomers { get; set; }

    public string TextForWeb { get; set; }

    public bool? SwWeighable { get; set; }

    public string PromotionBarcodes { get; set; }
}