// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EM.Comax.ShukHerzel.Models.Models;

public partial class Promotion
{
    public long Id { get; set; }

    public long CompanyId { get; set; }

    public long BranchId { get; set; }

    public DateTime CreatedDateTime { get; set; }

    public bool IsTransferredToOper { get; set; }

    public DateTime? TransferredDateTime { get; set; }

    public bool IsBad { get; set; }

    public Guid OperationGuid { get; set; }

    public string AnotherBarcodes { get; set; }

    public string Kod { get; set; }

    public string ItemKod { get; set; }

    public string Nm { get; set; }

    public string RemarkForPrint { get; set; }

    public string Nature { get; set; }

    public string FromDate { get; set; }

    public string ToDate { get; set; }

    public string SwActive { get; set; }

    public string SwSunday { get; set; }

    public string ActiveForHourSunday { get; set; }

    public string ActiveUpToHourSunday { get; set; }

    public string SwMonday { get; set; }

    public string ActiveForHourMonday { get; set; }

    public string ActiveUpToHourMonday { get; set; }

    public string SwTuesday { get; set; }

    public string ActiveForHourTuesday { get; set; }

    public string ActiveUpToHourTuesday { get; set; }

    public string SwWednesday { get; set; }

    public string ActiveForHourWednesday { get; set; }

    public string ActiveUpToHourWednesday { get; set; }

    public string SwThursday { get; set; }

    public string ActiveForHourThursday { get; set; }

    public string ActiveUpToHourThursday { get; set; }

    public string SwFriday { get; set; }

    public string ActiveForHourFriday { get; set; }

    public string ActiveUpToHourFriday { get; set; }

    public string SwSaturday { get; set; }

    public string ActiveForHourSaturday { get; set; }

    public string ActiveUpToHourSaturday { get; set; }

    public string SwKupa { get; set; }

    public string RealizationPercent { get; set; }

    public string SwAllBranches { get; set; }

    public string SwAllCustomers { get; set; }

    public string SwAllItems { get; set; }

    public string SwPrintNm { get; set; }

    public string SwSignageOnly { get; set; }

    public string SwCasing { get; set; }

    public string SwIncludeRelatedCompStores { get; set; }

    public string PromotionType { get; set; }

    public string SupplierName { get; set; }

    public string Quantity { get; set; }

    public string MinQty { get; set; }

    public string MaxQty { get; set; }

    public string Total { get; set; }

    public string GetGiftItem { get; set; }

    public string GetRemark { get; set; }

    public string GetCmt { get; set; }

    public string SwIncludeNetoItem { get; set; }

    public string GetTotal { get; set; }

    public string GetDiscountPrecent { get; set; }

    public string GetDiscountTotal { get; set; }

    public string TotalForActivate { get; set; }

    public string SwSameDiffItems { get; set; }

    public string WithoutPrintContent { get; set; }

    public string Rating { get; set; }

    public string NoAdditionalDiscounts { get; set; }

    public string WithoutPresentList { get; set; }

    public string WithoutPrintingData { get; set; }

    public string Classified { get; set; }

    public string MaxInDoc { get; set; }

    public string SwCalcEnd { get; set; }

    public string SwCheckForTotalNeto { get; set; }

    public string SwCalcDis { get; set; }

    public string SwMustPayClubCredit { get; set; }

    public string SpurMessage { get; set; }

    public string SpurTotal { get; set; }

    public string SpurQty { get; set; }

    public string DoubleDeals { get; set; }

    public string WithoutMarkOnWeb { get; set; }

    public string SwSupplierCharge { get; set; }

    public string SupplierForCharge { get; set; }

    public string PriceListForCharge { get; set; }

    public string SwChargeType { get; set; }

    public string TotalDiscountCharge { get; set; }

    public string SwOperative { get; set; }

    public string SwNoSplit { get; set; }

    public string MustAdditionalPromotions { get; set; }

    public string TextForWeb { get; set; }

    public string TextToPrint { get; set; }

    public string TextToPrintUnicode { get; set; }

    public string ApprovedSignage { get; set; }

    public string Tag1 { get; set; }

    public string Tag2 { get; set; }

    public string SelfFinancingReward { get; set; }

    public string PromoForRealization { get; set; }

    public string CostOfRealizingGift { get; set; }

    public string SelectPromoToMultiply { get; set; }

    public string SelectPromoToNotMultiply { get; set; }

    public string Stores { get; set; }

    public string CustomerGrp { get; set; }

    public string Items { get; set; }

    public string Suppliers { get; set; }

    public string ItemsGrp { get; set; }

    public string ItemsSubGrp { get; set; }

    public string ItemsDep { get; set; }

    public string ItemsModel { get; set; }

    public string ItemsVarious { get; set; }

    public string ItemsAttribute1 { get; set; }

    public string ItemsAttribute2 { get; set; }

    public string ItemsAttribute3 { get; set; }

    public string GetItems { get; set; }

    public string GetSuppliers { get; set; }

    public string GetItemsGrp { get; set; }

    public string GetItemsSubGrp { get; set; }

    public string GetItemsDep { get; set; }

    public string GetItemsModel { get; set; }

    public string GetItemsAttribute1 { get; set; }

    public string GetItemsAttribute2 { get; set; }

    public string GetItemsAttribute3 { get; set; }

    public string ErrorMessage { get; set; }

    public string ClassifiedNm { get; set; }

    public string CounterGetInSale { get; set; }

    public string SameGetAndBuy { get; set; }

    public string SwNotForShelfSignage { get; set; }
}