// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace EM.Comax.ShukHerzel.Models.Models;

public partial class ShukHerzelEntities : DbContext
{
    public ShukHerzelEntities(DbContextOptions<ShukHerzelEntities> options)
        : base(options)
    {
    }

    public virtual DbSet<AllItem> AllItems { get; set; }

    public virtual DbSet<BadItemLog> BadItemLogs { get; set; }

    public virtual DbSet<Branch> Branches { get; set; }

    public virtual DbSet<Company> Companies { get; set; }

    public virtual DbSet<Configuration> Configurations { get; set; }

    public virtual DbSet<ErrorLog> ErrorLogs { get; set; }

    public virtual DbSet<GuidToFlow> GuidToFlows { get; set; }

    public virtual DbSet<Item> Items { get; set; }

    public virtual DbSet<PriceUpdate> PriceUpdates { get; set; }

    public virtual DbSet<Promotion> Promotions { get; set; }

    public virtual DbSet<ServiceLog> ServiceLogs { get; set; }

    public virtual DbSet<TraceLog> TraceLogs { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AllItem>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__allItems__3214EC27F35E7269");

            entity.ToTable("allItems", "Temp");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.AdditionalConversion).HasMaxLength(50);
            entity.Property(e => e.AlternateId)
                .HasMaxLength(50)
                .HasColumnName("AlternateID");
            entity.Property(e => e.AmaraBy).HasMaxLength(200);
            entity.Property(e => e.AnotherBarkods).HasMaxLength(200);
            entity.Property(e => e.ArchiveDate).HasMaxLength(50);
            entity.Property(e => e.AtarDescription).HasMaxLength(200);
            entity.Property(e => e.Attribute1).HasMaxLength(200);
            entity.Property(e => e.Attribute1Code).HasMaxLength(50);
            entity.Property(e => e.Attribute2).HasMaxLength(200);
            entity.Property(e => e.Attribute2Code).HasMaxLength(50);
            entity.Property(e => e.Attribute3).HasMaxLength(200);
            entity.Property(e => e.Attribute3Code).HasMaxLength(50);
            entity.Property(e => e.Attribute4).HasMaxLength(200);
            entity.Property(e => e.Attribute4Code).HasMaxLength(50);
            entity.Property(e => e.Attribute5).HasMaxLength(200);
            entity.Property(e => e.Attribute5Code).HasMaxLength(50);
            entity.Property(e => e.Barcode).HasMaxLength(50);
            entity.Property(e => e.BaseDocNumber).HasMaxLength(50);
            entity.Property(e => e.BaseLine).HasMaxLength(50);
            entity.Property(e => e.BaseReference).HasMaxLength(50);
            entity.Property(e => e.BaseYear).HasMaxLength(50);
            entity.Property(e => e.BlockPurchaseDate).HasMaxLength(50);
            entity.Property(e => e.BlockSalesDate).HasMaxLength(50);
            entity.Property(e => e.BonosFline).HasMaxLength(50);
            entity.Property(e => e.BonosTline).HasMaxLength(50);
            entity.Property(e => e.BranchId).HasColumnName("BranchID");
            entity.Property(e => e.CmtAmara).HasMaxLength(50);
            entity.Property(e => e.CmtAmara2).HasMaxLength(50);
            entity.Property(e => e.CmtAmr3).HasMaxLength(50);
            entity.Property(e => e.Colestrol).HasMaxLength(50);
            entity.Property(e => e.ColorGrp).HasMaxLength(200);
            entity.Property(e => e.CompanyId).HasColumnName("CompanyID");
            entity.Property(e => e.Content).HasMaxLength(50);
            entity.Property(e => e.ContentMeasure).HasMaxLength(50);
            entity.Property(e => e.ContentUnit).HasMaxLength(50);
            entity.Property(e => e.Conversion).HasMaxLength(50);
            entity.Property(e => e.ConversionQuantity).HasMaxLength(50);
            entity.Property(e => e.CorrectionDiscountPercent).HasMaxLength(50);
            entity.Property(e => e.CorrectionPrice).HasMaxLength(50);
            entity.Property(e => e.CorrectionQuantity).HasMaxLength(50);
            entity.Property(e => e.CreatedDateTime)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysdatetime())")
                .HasColumnName("createdDateTime");
            entity.Property(e => e.CurrentStoreId)
                .HasMaxLength(50)
                .HasColumnName("CurrentStoreID");
            entity.Property(e => e.CustomerMakat).HasMaxLength(50);
            entity.Property(e => e.CustomersOrders).HasMaxLength(50);
            entity.Property(e => e.Department).HasMaxLength(200);
            entity.Property(e => e.DepartmentCode).HasMaxLength(50);
            entity.Property(e => e.DepartmentEnglishName).HasMaxLength(200);
            entity.Property(e => e.DiagonalOptic).HasMaxLength(50);
            entity.Property(e => e.DiscountPercent).HasMaxLength(50);
            entity.Property(e => e.DiscountTotal).HasMaxLength(50);
            entity.Property(e => e.DownloadPriceTransparencyAfter48Hours).HasMaxLength(50);
            entity.Property(e => e.Energia).HasMaxLength(50);
            entity.Property(e => e.EnglishName).HasMaxLength(200);
            entity.Property(e => e.FullIngredientsReplace).HasMaxLength(10);
            entity.Property(e => e.GroupCode).HasMaxLength(50);
            entity.Property(e => e.GroupEnglishName).HasMaxLength(200);
            entity.Property(e => e.GroupName).HasMaxLength(200);
            entity.Property(e => e.Height).HasMaxLength(50);
            entity.Property(e => e.HeightOptic).HasMaxLength(50);
            entity.Property(e => e.HeightSize).HasMaxLength(50);
            entity.Property(e => e.Helbonim).HasMaxLength(50);
            entity.Property(e => e.HierarchyUpdate).HasMaxLength(10);
            entity.Property(e => e.Ingredients).HasMaxLength(200);
            entity.Property(e => e.InternalAmara).HasMaxLength(50);
            entity.Property(e => e.IsBad).HasColumnName("isBad");
            entity.Property(e => e.IsControlledItem).HasMaxLength(50);
            entity.Property(e => e.IsGiftCardPurchase).HasMaxLength(10);
            entity.Property(e => e.IsTransferredToOper).HasColumnName("isTransferredToOper");
            entity.Property(e => e.ItemColorId)
                .HasMaxLength(50)
                .HasColumnName("ItemColor_ID");
            entity.Property(e => e.ItemColorName)
                .HasMaxLength(200)
                .HasColumnName("ItemColor_Name");
            entity.Property(e => e.ItemData).HasMaxLength(200);
            entity.Property(e => e.ItemModelId)
                .HasMaxLength(50)
                .HasColumnName("ItemModel_ID");
            entity.Property(e => e.ItemModelName)
                .HasMaxLength(200)
                .HasColumnName("ItemModel_Name");
            entity.Property(e => e.ItemSizeId)
                .HasMaxLength(50)
                .HasColumnName("ItemSize_ID");
            entity.Property(e => e.ItemSizeName)
                .HasMaxLength(200)
                .HasColumnName("ItemSize_Name");
            entity.Property(e => e.ItemsTree).HasMaxLength(200);
            entity.Property(e => e.KodSet).HasMaxLength(50);
            entity.Property(e => e.Length).HasMaxLength(50);
            entity.Property(e => e.LengthOptic).HasMaxLength(50);
            entity.Property(e => e.LengthSize).HasMaxLength(50);
            entity.Property(e => e.LimitAge).HasMaxLength(50);
            entity.Property(e => e.Line).HasMaxLength(50);
            entity.Property(e => e.LinkWebSite).HasMaxLength(200);
            entity.Property(e => e.Manufacturer).HasMaxLength(200);
            entity.Property(e => e.ManufacturerCode).HasMaxLength(50);
            entity.Property(e => e.ManufacturingCountry).HasMaxLength(200);
            entity.Property(e => e.MatchingItemId)
                .HasMaxLength(50)
                .HasColumnName("MatchingItemID");
            entity.Property(e => e.MatchingItemQuantity).HasMaxLength(50);
            entity.Property(e => e.MaxQtyForSale).HasMaxLength(50);
            entity.Property(e => e.MaxQuantityInOrder).HasMaxLength(50);
            entity.Property(e => e.MaxStock).HasMaxLength(50);
            entity.Property(e => e.MaximumStock).HasMaxLength(50);
            entity.Property(e => e.MhrMivza).HasMaxLength(50);
            entity.Property(e => e.MidaAmr3).HasMaxLength(200);
            entity.Property(e => e.MinQtyForSale).HasMaxLength(50);
            entity.Property(e => e.MinStock).HasMaxLength(50);
            entity.Property(e => e.MinimumStock).HasMaxLength(50);
            entity.Property(e => e.MirshamPhrmaSoft)
                .HasMaxLength(50)
                .HasColumnName("Mirsham_PhrmaSoft");
            entity.Property(e => e.Name).HasMaxLength(200);
            entity.Property(e => e.NameInWeb).HasMaxLength(200);
            entity.Property(e => e.Nava).HasMaxLength(50);
            entity.Property(e => e.NetPrice).HasMaxLength(50);
            entity.Property(e => e.NmMashlim)
                .HasMaxLength(200)
                .HasColumnName("Nm_Mashlim");
            entity.Property(e => e.NoDiscount).HasMaxLength(50);
            entity.Property(e => e.NosafKod10)
                .HasMaxLength(50)
                .HasColumnName("NosafKod_10");
            entity.Property(e => e.NosafKod2)
                .HasMaxLength(50)
                .HasColumnName("NosafKod_2");
            entity.Property(e => e.NosafKod3)
                .HasMaxLength(50)
                .HasColumnName("NosafKod_3");
            entity.Property(e => e.NosafKod4)
                .HasMaxLength(50)
                .HasColumnName("NosafKod_4");
            entity.Property(e => e.NosafKod5)
                .HasMaxLength(50)
                .HasColumnName("NosafKod_5");
            entity.Property(e => e.NosafKod6)
                .HasMaxLength(50)
                .HasColumnName("NosafKod_6");
            entity.Property(e => e.NosafKod7)
                .HasMaxLength(50)
                .HasColumnName("NosafKod_7");
            entity.Property(e => e.NosafKod8)
                .HasMaxLength(50)
                .HasColumnName("NosafKod_8");
            entity.Property(e => e.NosafKod9)
                .HasMaxLength(50)
                .HasColumnName("NosafKod_9");
            entity.Property(e => e.NosafNm10)
                .HasMaxLength(200)
                .HasColumnName("NosafNm_10");
            entity.Property(e => e.NosafNm2)
                .HasMaxLength(200)
                .HasColumnName("NosafNm_2");
            entity.Property(e => e.NosafNm3)
                .HasMaxLength(200)
                .HasColumnName("NosafNm_3");
            entity.Property(e => e.NosafNm4)
                .HasMaxLength(200)
                .HasColumnName("NosafNm_4");
            entity.Property(e => e.NosafNm5)
                .HasMaxLength(200)
                .HasColumnName("NosafNm_5");
            entity.Property(e => e.NosafNm6)
                .HasMaxLength(200)
                .HasColumnName("NosafNm_6");
            entity.Property(e => e.NosafNm7)
                .HasMaxLength(200)
                .HasColumnName("NosafNm_7");
            entity.Property(e => e.NosafNm8)
                .HasMaxLength(200)
                .HasColumnName("NosafNm_8");
            entity.Property(e => e.NosafNm9)
                .HasMaxLength(200)
                .HasColumnName("NosafNm_9");
            entity.Property(e => e.NotShowInWeb).HasMaxLength(10);
            entity.Property(e => e.OldId)
                .HasMaxLength(50)
                .HasColumnName("OldID");
            entity.Property(e => e.OpenDate).HasMaxLength(50);
            entity.Property(e => e.OperationGuid)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("operationGuid");
            entity.Property(e => e.Pahmemot).HasMaxLength(50);
            entity.Property(e => e.PikadonCmt).HasMaxLength(200);
            entity.Property(e => e.Price).HasMaxLength(50);
            entity.Property(e => e.PriceNis)
                .HasMaxLength(50)
                .HasColumnName("PriceNIS");
            entity.Property(e => e.PriceUsd)
                .HasMaxLength(50)
                .HasColumnName("PriceUSD");
            entity.Property(e => e.PromoId)
                .HasMaxLength(50)
                .HasColumnName("PromoID");
            entity.Property(e => e.PromoRank).HasMaxLength(50);
            entity.Property(e => e.PrtC).HasMaxLength(50);
            entity.Property(e => e.PurchasingAccountId)
                .HasMaxLength(50)
                .HasColumnName("PurchasingAccountID");
            entity.Property(e => e.QtyType).HasMaxLength(50);
            entity.Property(e => e.Quantity).HasMaxLength(50);
            entity.Property(e => e.Radius).HasMaxLength(50);
            entity.Property(e => e.RefLine)
                .HasMaxLength(50)
                .HasColumnName("Ref_Line");
            entity.Property(e => e.RejectTypeId)
                .HasMaxLength(50)
                .HasColumnName("RejectTypeID");
            entity.Property(e => e.SalesAccountId)
                .HasMaxLength(50)
                .HasColumnName("SalesAccountID");
            entity.Property(e => e.SerialNo).HasMaxLength(50);
            entity.Property(e => e.SetId).HasMaxLength(50);
            entity.Property(e => e.SetModelProperties).HasMaxLength(10);
            entity.Property(e => e.Shumanim).HasMaxLength(50);
            entity.Property(e => e.Size).HasMaxLength(50);
            entity.Property(e => e.StiaAm)
                .HasMaxLength(50)
                .HasColumnName("StiaAM");
            entity.Property(e => e.StoreId)
                .HasMaxLength(50)
                .HasColumnName("StoreID");
            entity.Property(e => e.SubGroup)
                .HasMaxLength(200)
                .HasColumnName("Sub_Group");
            entity.Property(e => e.SubGroupCode)
                .HasMaxLength(50)
                .HasColumnName("Sub_GroupCode");
            entity.Property(e => e.SubGroupEnglishName)
                .HasMaxLength(200)
                .HasColumnName("Sub_GroupEnglishName");
            entity.Property(e => e.SuperDepartment).HasMaxLength(200);
            entity.Property(e => e.SuperDepartmentCode).HasMaxLength(50);
            entity.Property(e => e.SupplierCatalogNumber).HasMaxLength(200);
            entity.Property(e => e.SupplierCurrency).HasMaxLength(50);
            entity.Property(e => e.SupplierId)
                .HasMaxLength(50)
                .HasColumnName("SupplierID");
            entity.Property(e => e.SupplierName).HasMaxLength(200);
            entity.Property(e => e.SupplierPrice).HasMaxLength(50);
            entity.Property(e => e.SupplierPriceNet).HasMaxLength(50);
            entity.Property(e => e.SupplierShekelPrice).HasMaxLength(50);
            entity.Property(e => e.SupplierShekelPriceNet).HasMaxLength(50);
            entity.Property(e => e.SuppliersOrders).HasMaxLength(50);
            entity.Property(e => e.SwAlcohol).HasMaxLength(50);
            entity.Property(e => e.SwBonos).HasMaxLength(10);
            entity.Property(e => e.SwMustCmtInKupa).HasMaxLength(50);
            entity.Property(e => e.SwPikadon).HasMaxLength(50);
            entity.Property(e => e.SwSerialy).HasMaxLength(10);
            entity.Property(e => e.SwWeighable).HasMaxLength(10);
            entity.Property(e => e.Thickness).HasMaxLength(50);
            entity.Property(e => e.TotalSum).HasMaxLength(50);
            entity.Property(e => e.TrailingItem).HasMaxLength(50);
            entity.Property(e => e.TransferredDateTime)
                .HasPrecision(3)
                .HasColumnName("transferredDateTime");
            entity.Property(e => e.UnitsQuantity).HasMaxLength(50);
            entity.Property(e => e.Volume).HasMaxLength(50);
            entity.Property(e => e.VolumeSize).HasMaxLength(50);
            entity.Property(e => e.WarrantyMonths).HasMaxLength(50);
            entity.Property(e => e.WarrantyRemark).HasMaxLength(200);
            entity.Property(e => e.WarrantySupplier).HasMaxLength(50);
            entity.Property(e => e.WebCategory).HasMaxLength(200);
            entity.Property(e => e.WebCategoryNm).HasMaxLength(200);
            entity.Property(e => e.WebColor).HasMaxLength(50);
            entity.Property(e => e.WebColorNm).HasMaxLength(200);
            entity.Property(e => e.WebDelvDesc).HasMaxLength(200);
            entity.Property(e => e.WebDep).HasMaxLength(50);
            entity.Property(e => e.WebDepNm).HasMaxLength(200);
            entity.Property(e => e.WebDesc).HasMaxLength(200);
            entity.Property(e => e.WebDesc2).HasMaxLength(200);
            entity.Property(e => e.WebGrp).HasMaxLength(50);
            entity.Property(e => e.WebGrpNm).HasMaxLength(200);
            entity.Property(e => e.WebInstruction).HasMaxLength(200);
            entity.Property(e => e.WebManufacturer).HasMaxLength(200);
            entity.Property(e => e.WebManufacturerCode).HasMaxLength(50);
            entity.Property(e => e.WebNosafKod2)
                .HasMaxLength(50)
                .HasColumnName("WebNosafKod_2");
            entity.Property(e => e.WebNosafNm2)
                .HasMaxLength(200)
                .HasColumnName("WebNosafNm_2");
            entity.Property(e => e.WebRating).HasMaxLength(50);
            entity.Property(e => e.WebShortName).HasMaxLength(200);
            entity.Property(e => e.WebSubGroup)
                .HasMaxLength(50)
                .HasColumnName("WebSub_Group");
            entity.Property(e => e.WebSubGroupNm)
                .HasMaxLength(200)
                .HasColumnName("WebSub_GroupNm");
            entity.Property(e => e.Weight).HasMaxLength(50);
            entity.Property(e => e.WeightSize).HasMaxLength(50);
            entity.Property(e => e.Width).HasMaxLength(50);
            entity.Property(e => e.WidthSize).HasMaxLength(50);
            entity.Property(e => e.WorkByAlternateId)
                .HasMaxLength(10)
                .HasColumnName("WorkByAlternateID");
            entity.Property(e => e.XmlId)
                .HasMaxLength(50)
                .HasColumnName("Xml_ID");
        });

        modelBuilder.Entity<BadItemLog>(entity =>
        {
            entity.ToTable("BadItemLog", "Log");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Barcode).HasMaxLength(50);
            entity.Property(e => e.Guid).HasMaxLength(50);
            entity.Property(e => e.Message).HasMaxLength(500);
            entity.Property(e => e.TimeStamp).HasColumnType("datetime");
        });

        modelBuilder.Entity<Branch>(entity =>
        {
            entity.ToTable("Branch", "Management");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.BranchName).HasMaxLength(50);
            entity.Property(e => e.ComaxPriceListId).HasColumnName("ComaxPriceListID");
            entity.Property(e => e.ComaxStoreId).HasColumnName("ComaxStoreID");
            entity.Property(e => e.CompanyId).HasColumnName("CompanyID");
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(250);
            entity.Property(e => e.EslStoreId)
                .HasMaxLength(250)
                .HasColumnName("EslStoreID");
            entity.Property(e => e.LastCatalogTimeStamp).HasColumnType("datetime");
            entity.Property(e => e.LastPriceTimeStamp).HasColumnType("datetime");
            entity.Property(e => e.LastPromotionTimeStamp).HasColumnType("datetime");
            entity.Property(e => e.LastRun).HasColumnType("datetime");
            entity.Property(e => e.PromotionStoreListId).HasColumnName("PromotionStoreListID");
        });

        modelBuilder.Entity<Company>(entity =>
        {
            entity.ToTable("Company", "Management");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Description)
                .HasMaxLength(250)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Configuration>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Configur__3214EC2762794FE9");

            entity.ToTable("Configuration", "Management");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.ComaxApiUrl).HasMaxLength(200);
            entity.Property(e => e.CompanyId).HasColumnName("CompanyID");
            entity.Property(e => e.CreatedDateTime)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.CustomerId).HasColumnName("CustomerID");
            entity.Property(e => e.DepartmentId).HasColumnName("DepartmentID");
            entity.Property(e => e.EslApiKey).HasMaxLength(200);
            entity.Property(e => e.EslUrl).HasMaxLength(200);
            entity.Property(e => e.ExtraCatalogParamsJson).HasMaxLength(200);
            entity.Property(e => e.GroupId).HasColumnName("GroupID");
            entity.Property(e => e.ItemColorId).HasColumnName("ItemColorID");
            entity.Property(e => e.ItemId).HasColumnName("ItemID");
            entity.Property(e => e.ItemModelId).HasColumnName("ItemModelID");
            entity.Property(e => e.ItemSizeId).HasColumnName("ItemSizeID");
            entity.Property(e => e.LoginId)
                .HasMaxLength(100)
                .HasColumnName("LoginID");
            entity.Property(e => e.LoginPassword).HasMaxLength(100);
            entity.Property(e => e.ModifiedDateTime).HasPrecision(3);
            entity.Property(e => e.PromotionLastUpdatedDate).HasPrecision(3);
            entity.Property(e => e.PromotionParamsJson).HasMaxLength(200);
            entity.Property(e => e.PromotionStoreList).HasMaxLength(50);
            entity.Property(e => e.StoreIdforOpenOrdersOffset).HasColumnName("StoreIDForOpenOrdersOffset");
            entity.Property(e => e.SubGroupId).HasColumnName("Sub_GroupID");
            entity.Property(e => e.SupplierId).HasColumnName("SupplierID");
        });

        modelBuilder.Entity<ErrorLog>(entity =>
        {
            entity.HasKey(e => e.LogId);

            entity.ToTable("ErrorLog", "Log");

            entity.Property(e => e.LogId).HasColumnName("LogID");
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.ExceptionMessage).HasMaxLength(1000);
            entity.Property(e => e.InnerException).HasMaxLength(2500);
            entity.Property(e => e.Request).HasMaxLength(2500);
            entity.Property(e => e.SourceName).HasMaxLength(50);
        });

        modelBuilder.Entity<GuidToFlow>(entity =>
        {
            entity.ToTable("GuidToFlow");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.BranchId).HasColumnName("BranchID");
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(sysdatetime())")
                .HasColumnType("datetime");
            entity.Property(e => e.Guid).HasMaxLength(250);
        });

        modelBuilder.Entity<Item>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__items__3214EC27253B7B12");

            entity.ToTable("items", "Oper");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Barcode)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.BranchId).HasColumnName("BranchID");
            entity.Property(e => e.CompanyId).HasColumnName("CompanyID");
            entity.Property(e => e.Content).HasMaxLength(50);
            entity.Property(e => e.ContentMeasure).HasMaxLength(50);
            entity.Property(e => e.ContentPrice).HasColumnType("money");
            entity.Property(e => e.ContentUnit).HasMaxLength(50);
            entity.Property(e => e.CreateDateTime)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.GetCmt).HasMaxLength(50);
            entity.Property(e => e.GetDiscountPrecent).HasMaxLength(50);
            entity.Property(e => e.GetDiscountTotal).HasMaxLength(50);
            entity.Property(e => e.GetTotal).HasMaxLength(50);
            entity.Property(e => e.IsSentToEsl).HasDefaultValue(false);
            entity.Property(e => e.ManufacturingCountry).HasMaxLength(100);
            entity.Property(e => e.Name).HasMaxLength(200);
            entity.Property(e => e.OperationGuid).HasColumnName("operationGuid");
            entity.Property(e => e.Price).HasColumnType("money");
            entity.Property(e => e.PromotionBarcodes).HasMaxLength(200);
            entity.Property(e => e.PromotionFromDate).HasPrecision(3);
            entity.Property(e => e.PromotionKod)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.PromotionMaxQty).HasMaxLength(50);
            entity.Property(e => e.PromotionMinQty).HasMaxLength(50);
            entity.Property(e => e.PromotionQuantity).HasMaxLength(50);
            entity.Property(e => e.PromotionToDate).HasPrecision(3);
            entity.Property(e => e.Quantity).HasColumnType("decimal(18, 3)");
            entity.Property(e => e.Rating).HasMaxLength(50);
            entity.Property(e => e.SentToEslDate).HasPrecision(3);
            entity.Property(e => e.Size).HasMaxLength(50);
            entity.Property(e => e.TextForWeb).HasMaxLength(500);
            entity.Property(e => e.TotalForActivate).HasMaxLength(50);
            entity.Property(e => e.TotalPromotionPrice).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TrailingItem).HasMaxLength(50);
        });

        modelBuilder.Entity<PriceUpdate>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__PriceUpd__3214EC27CEF2B27A");

            entity.ToTable("PriceUpdates", "Temp");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.AlternateId)
                .HasMaxLength(50)
                .HasColumnName("AlternateID");
            entity.Property(e => e.Barcode).HasMaxLength(50);
            entity.Property(e => e.BranchId).HasColumnName("BranchID");
            entity.Property(e => e.CompanyId).HasColumnName("CompanyID");
            entity.Property(e => e.CreatedDateTime)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysdatetime())")
                .HasColumnName("createdDateTime");
            entity.Property(e => e.Currency).HasMaxLength(50);
            entity.Property(e => e.IsIncludeVat).HasMaxLength(50);
            entity.Property(e => e.IsTransferredToOper).HasColumnName("isTransferredToOper");
            entity.Property(e => e.Name).HasMaxLength(200);
            entity.Property(e => e.NetPrice).HasMaxLength(50);
            entity.Property(e => e.OperationEndDate).HasMaxLength(200);
            entity.Property(e => e.OperationGuid).HasColumnName("operationGuid");
            entity.Property(e => e.Price).HasMaxLength(50);
            entity.Property(e => e.PriceListId)
                .HasMaxLength(50)
                .HasColumnName("PriceListID");
            entity.Property(e => e.SalePrice).HasMaxLength(50);
            entity.Property(e => e.ShekelNetPrice).HasMaxLength(50);
            entity.Property(e => e.ShekelPrice).HasMaxLength(50);
            entity.Property(e => e.Size).HasMaxLength(50);
            entity.Property(e => e.TransferredDateTime)
                .HasPrecision(3)
                .HasColumnName("transferredDateTime");
            entity.Property(e => e.XmlId)
                .HasMaxLength(50)
                .HasColumnName("Xml_ID");
        });

        modelBuilder.Entity<Promotion>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__promotio__3214EC27E81EBF53");

            entity.ToTable("promotions", "Temp");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.ActiveForHourFriday)
                .HasMaxLength(50)
                .HasColumnName("ActiveFor_Hour_Friday");
            entity.Property(e => e.ActiveForHourMonday)
                .HasMaxLength(50)
                .HasColumnName("ActiveFor_Hour_Monday");
            entity.Property(e => e.ActiveForHourSaturday)
                .HasMaxLength(50)
                .HasColumnName("ActiveFor_Hour_Saturday");
            entity.Property(e => e.ActiveForHourSunday)
                .HasMaxLength(50)
                .HasColumnName("ActiveFor_Hour_Sunday");
            entity.Property(e => e.ActiveForHourThursday)
                .HasMaxLength(50)
                .HasColumnName("ActiveFor_Hour_Thursday");
            entity.Property(e => e.ActiveForHourTuesday)
                .HasMaxLength(50)
                .HasColumnName("ActiveFor_Hour_Tuesday");
            entity.Property(e => e.ActiveForHourWednesday)
                .HasMaxLength(50)
                .HasColumnName("ActiveFor_Hour_Wednesday");
            entity.Property(e => e.ActiveUpToHourFriday)
                .HasMaxLength(50)
                .HasColumnName("ActiveUpTo_Hour_Friday");
            entity.Property(e => e.ActiveUpToHourMonday)
                .HasMaxLength(50)
                .HasColumnName("ActiveUpTo_Hour_Monday");
            entity.Property(e => e.ActiveUpToHourSaturday)
                .HasMaxLength(50)
                .HasColumnName("ActiveUpTo_Hour_Saturday");
            entity.Property(e => e.ActiveUpToHourSunday)
                .HasMaxLength(50)
                .HasColumnName("ActiveUpTo_Hour_Sunday");
            entity.Property(e => e.ActiveUpToHourThursday)
                .HasMaxLength(50)
                .HasColumnName("ActiveUpTo_Hour_Thursday");
            entity.Property(e => e.ActiveUpToHourTuesday)
                .HasMaxLength(50)
                .HasColumnName("ActiveUpTo_Hour_Tuesday");
            entity.Property(e => e.ActiveUpToHourWednesday)
                .HasMaxLength(50)
                .HasColumnName("ActiveUpTo_Hour_Wednesday");
            entity.Property(e => e.AnotherBarcodes).HasMaxLength(200);
            entity.Property(e => e.ApprovedSignage).HasMaxLength(10);
            entity.Property(e => e.BranchId).HasColumnName("BranchID");
            entity.Property(e => e.Classified).HasMaxLength(50);
            entity.Property(e => e.ClassifiedNm).HasMaxLength(200);
            entity.Property(e => e.CompanyId).HasColumnName("CompanyID");
            entity.Property(e => e.CostOfRealizingGift).HasMaxLength(50);
            entity.Property(e => e.CounterGetInSale)
                .HasMaxLength(50)
                .HasColumnName("CounterGet_InSale");
            entity.Property(e => e.CreatedDateTime)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysdatetime())")
                .HasColumnName("createdDateTime");
            entity.Property(e => e.CustomerGrp).HasMaxLength(2000);
            entity.Property(e => e.DoubleDeals).HasMaxLength(10);
            entity.Property(e => e.ErrorMessage).HasMaxLength(200);
            entity.Property(e => e.FromDate).HasMaxLength(50);
            entity.Property(e => e.GetCmt).HasMaxLength(50);
            entity.Property(e => e.GetDiscountPrecent).HasMaxLength(50);
            entity.Property(e => e.GetDiscountTotal).HasMaxLength(50);
            entity.Property(e => e.GetGiftItem).HasMaxLength(50);
            entity.Property(e => e.GetItems).HasMaxLength(2000);
            entity.Property(e => e.GetItemsAttribute1).HasMaxLength(2000);
            entity.Property(e => e.GetItemsAttribute2).HasMaxLength(2000);
            entity.Property(e => e.GetItemsAttribute3).HasMaxLength(2000);
            entity.Property(e => e.GetItemsDep).HasMaxLength(2000);
            entity.Property(e => e.GetItemsGrp).HasMaxLength(2000);
            entity.Property(e => e.GetItemsModel).HasMaxLength(2000);
            entity.Property(e => e.GetItemsSubGrp).HasMaxLength(2000);
            entity.Property(e => e.GetRemark).HasMaxLength(200);
            entity.Property(e => e.GetSuppliers).HasMaxLength(2000);
            entity.Property(e => e.GetTotal).HasMaxLength(50);
            entity.Property(e => e.IsBad).HasColumnName("isBad");
            entity.Property(e => e.IsTransferredToOper).HasColumnName("isTransferredToOper");
            entity.Property(e => e.ItemKod).HasMaxLength(50);
            entity.Property(e => e.Items).HasMaxLength(2000);
            entity.Property(e => e.ItemsAttribute1).HasMaxLength(2000);
            entity.Property(e => e.ItemsAttribute2).HasMaxLength(2000);
            entity.Property(e => e.ItemsAttribute3).HasMaxLength(2000);
            entity.Property(e => e.ItemsDep).HasMaxLength(2000);
            entity.Property(e => e.ItemsGrp).HasMaxLength(2000);
            entity.Property(e => e.ItemsModel).HasMaxLength(2000);
            entity.Property(e => e.ItemsSubGrp).HasMaxLength(2000);
            entity.Property(e => e.ItemsVarious).HasMaxLength(2000);
            entity.Property(e => e.Kod).HasMaxLength(50);
            entity.Property(e => e.MaxInDoc).HasMaxLength(50);
            entity.Property(e => e.MaxQty).HasMaxLength(50);
            entity.Property(e => e.MinQty).HasMaxLength(50);
            entity.Property(e => e.MustAdditionalPromotions).HasMaxLength(200);
            entity.Property(e => e.Nature).HasMaxLength(50);
            entity.Property(e => e.Nm).HasMaxLength(200);
            entity.Property(e => e.NoAdditionalDiscounts).HasMaxLength(10);
            entity.Property(e => e.OperationGuid)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("operationGuid");
            entity.Property(e => e.PriceListForCharge).HasMaxLength(50);
            entity.Property(e => e.PromoForRealization).HasMaxLength(50);
            entity.Property(e => e.PromotionType).HasMaxLength(50);
            entity.Property(e => e.Quantity).HasMaxLength(50);
            entity.Property(e => e.Rating).HasMaxLength(50);
            entity.Property(e => e.RealizationPercent).HasMaxLength(50);
            entity.Property(e => e.RemarkForPrint).HasMaxLength(200);
            entity.Property(e => e.SameGetAndBuy).HasMaxLength(200);
            entity.Property(e => e.SelectPromoToMultiply)
                .HasMaxLength(200)
                .HasColumnName("SelectPromo_ToMultiply");
            entity.Property(e => e.SelectPromoToNotMultiply)
                .HasMaxLength(200)
                .HasColumnName("SelectPromo_ToNotMultiply");
            entity.Property(e => e.SelfFinancingReward).HasMaxLength(10);
            entity.Property(e => e.SpurMessage).HasMaxLength(200);
            entity.Property(e => e.SpurQty).HasMaxLength(50);
            entity.Property(e => e.SpurTotal).HasMaxLength(50);
            entity.Property(e => e.Stores).HasMaxLength(2000);
            entity.Property(e => e.SupplierForCharge).HasMaxLength(50);
            entity.Property(e => e.SupplierName).HasMaxLength(200);
            entity.Property(e => e.Suppliers).HasMaxLength(2000);
            entity.Property(e => e.SwActive).HasMaxLength(10);
            entity.Property(e => e.SwAllBranches).HasMaxLength(10);
            entity.Property(e => e.SwAllCustomers).HasMaxLength(10);
            entity.Property(e => e.SwAllItems).HasMaxLength(10);
            entity.Property(e => e.SwCalcDis).HasMaxLength(10);
            entity.Property(e => e.SwCalcEnd).HasMaxLength(10);
            entity.Property(e => e.SwCasing).HasMaxLength(10);
            entity.Property(e => e.SwChargeType).HasMaxLength(10);
            entity.Property(e => e.SwCheckForTotalNeto)
                .HasMaxLength(10)
                .HasColumnName("SwCheck_ForTotalNeto");
            entity.Property(e => e.SwFriday).HasMaxLength(10);
            entity.Property(e => e.SwIncludeNetoItem).HasMaxLength(10);
            entity.Property(e => e.SwIncludeRelatedCompStores).HasMaxLength(10);
            entity.Property(e => e.SwKupa).HasMaxLength(10);
            entity.Property(e => e.SwMonday).HasMaxLength(10);
            entity.Property(e => e.SwMustPayClubCredit)
                .HasMaxLength(10)
                .HasColumnName("SwMustPay_ClubCredit");
            entity.Property(e => e.SwNoSplit).HasMaxLength(10);
            entity.Property(e => e.SwOperative).HasMaxLength(10);
            entity.Property(e => e.SwPrintNm).HasMaxLength(10);
            entity.Property(e => e.SwSameDiffItems).HasMaxLength(10);
            entity.Property(e => e.SwSaturday).HasMaxLength(10);
            entity.Property(e => e.SwSignageOnly).HasMaxLength(10);
            entity.Property(e => e.SwSunday).HasMaxLength(10);
            entity.Property(e => e.SwSupplierCharge).HasMaxLength(10);
            entity.Property(e => e.SwThursday).HasMaxLength(10);
            entity.Property(e => e.SwTuesday).HasMaxLength(10);
            entity.Property(e => e.SwWednesday).HasMaxLength(10);
            entity.Property(e => e.Tag1).HasMaxLength(50);
            entity.Property(e => e.Tag2).HasMaxLength(50);
            entity.Property(e => e.TextForWeb).HasMaxLength(500);
            entity.Property(e => e.TextToPrint).HasMaxLength(500);
            entity.Property(e => e.TextToPrintUnicode)
                .HasMaxLength(500)
                .HasColumnName("TextToPrint_Unicode");
            entity.Property(e => e.ToDate).HasMaxLength(50);
            entity.Property(e => e.Total).HasMaxLength(50);
            entity.Property(e => e.TotalDiscountCharge).HasMaxLength(50);
            entity.Property(e => e.TotalForActivate).HasMaxLength(50);
            entity.Property(e => e.TransferredDateTime)
                .HasPrecision(3)
                .HasColumnName("transferredDateTime");
            entity.Property(e => e.WithoutMarkOnWeb).HasMaxLength(50);
            entity.Property(e => e.WithoutPresentList).HasMaxLength(10);
            entity.Property(e => e.WithoutPrintContent).HasMaxLength(10);
            entity.Property(e => e.WithoutPrintingData).HasMaxLength(10);
        });

        modelBuilder.Entity<ServiceLog>(entity =>
        {
            entity.ToTable("ServiceLog", "Log");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Message).HasMaxLength(2000);
            entity.Property(e => e.TimeStamp).HasColumnType("datetime");
        });

        modelBuilder.Entity<TraceLog>(entity =>
        {
            entity.ToTable("TraceLog", "Log");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Request).HasMaxLength(2500);
            entity.Property(e => e.Response).HasMaxLength(2500);
            entity.Property(e => e.ResponseStatus).HasMaxLength(50);
            entity.Property(e => e.Url).HasMaxLength(2000);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}