// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EM.Comax.ShukHerzel.Models.Models;

public partial class TrailingItem
{
    public int Id { get; set; }

    public string Kod { get; set; }

    public decimal? Price { get; set; }
}